// LOCALHOST
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/6816d064e706acbd46c6e655
###
GET http://localhost:8080/contacts/6816d06be706acbd46c6e656
###
GET http://localhost:8080/contacts/6816d072e706acbd46c6e657

// RENDER
###
GET https://cse341-lesson-2b.onrender.com/contacts
###
GET https://cse341-lesson-2b.onrender.com/contacts/6816d064e706acbd46c6e655
###
GET https://cse341-lesson-2b.onrender.com/contacts/6816d06be706acbd46c6e656
###
GET https://cse341-lesson-2b.onrender.com/contacts/6816d072e706acbd46c6e657

// Lesson 3 LOCALHOST
### ADD a contact to the database
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Arthur",
    "lastName":"Pendragon",
    "email":"apendragon@camelot.net",
    "favoriteColor":"Blue",
    "birthday":"1/1/650"
}
### EDIT a contact in the database
PUT http://localhost:8080/contacts/68294ac0913d8879fe1d1fe9 HTTP/1.1
content-type: application/json

{
    "firstName":"Arthur",
    "lastName":"Pendragon",
    "email":"apendragon@camelot.net",
    "favoriteColor":"Orange",
    "birthday":"6/15/550"
}
### DELETE a contact from the database
DELETE http://localhost:8080/contacts/68294ac0913d8879fe1d1fe9 HTTP/1.1

// Lesson 3 RENDER
###
GET https://cse341-lesson-2b.onrender.com/contacts/68201d05f08b5cf516c0eef5 HTTP/1.1
###
POST https://cse341-lesson-2b.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Arthur",
    "lastName":"Pendragon",
    "email":"apendragon@camelot.net",
    "favoriteColor":"Blue",
    "birthday":"1/1/650"
}
###
PUT https://cse341-lesson-2b.onrender.com/contacts/68294c0e8a50c0566609add1 HTTP/1.1
content-type: application/json

{
    "firstName":"Arthur",
    "lastName":"Pendragon",
    "email":"apendragon@camelot.net",
    "favoriteColor":"Orange",
    "birthday":"6/15/550"
}
###
DELETE https://cse341-lesson-2b.onrender.com/contacts/68294c0e8a50c0566609add1 HTTP/1.1

